### ISSUE TITLE
Silent failure when a SASS file is not found in a bundle

### ISSUE THREAD

**Issue by dmatteo** [Munter/express-compile-sass#8]
Whenever a non existing `scss` file is included in another bundle using `@import`, the compiling silently fails, outputting just a grey page.

**Comment by Munter** [comment]
The test  just added has a missing import. But the test doesn't fail. I need more details to recreate the situation

**Comment by dmatteo** [comment]
Interesting.
Tomorrow I will try to recreate the issue where it first occurred and then creating a minimum setup for [re]testing it

**Comment by dmatteo** [comment]
```css
body * {display: none !important;} body:before {line-height: 1.5; display: block; z-index: 99999999; white-space: pre; font-family: "Courier New", monospace; font-size: 20px; color: black; margin: 10px; padding: 10px; border: 4px dashed red; margin-bottom: 10px; content: "express-compile-sass:\00000a  Syntax error in /app/assets/stylesheets/base.scss:47\00000afile to import not found or unreadable: "../javascripts/components/ElasticTextareaComponent/ElasticTextareaComponent.scss"\00000aCurrent dir: /Users/domo/projects/podio/frontend-rails/app/assets/stylesheets/";}
```

unescaped doueble quotes in `content`
